### ISSUE TITLE
Physical Activation Failing on eAPI

### ISSUE THREAD

**Issue by KyleBarton** [KyleBarton/CoffeeApiDotNet#11]
Right now all physical orders made through eAPI are failing to activate. This is due to an incorrect BIF URL in our app.config file. We need to change the value in the app.config production transform in order to fix this.

**Comment by KyleBarton** [comment]
#12 fixes this.

**Comment by KyleBarton** [comment]
SCR is complete and QA sign off is too. @abuckley1 awaiting your approval.

**Comment by abuckley1** [comment]
approved, PR can be merged and released.

**Comment by KyleBarton** [comment]
Production testing complete. Orders are now activating successfully.
