### ISSUE TITLE
Add correct DB IP address to the Registry on Web9

### ISSUE THREAD

**Issue by KyleBarton** [KyleBarton/CoffeeApiDotNet#6]
Right now, the IP address that web9 uses to connect to the database (via cliconfg.exe) is incorrect. We need to change it from 127.0.0.1 to 127.0.02. This change will be performed by @abuckley1. This is related to a breakage from #5

**Comment by KyleBarton** [comment]
In addition, we've identified an incorrect value in the Admin web.config file. We will be changing the value for DBIP from 128.0.0.2 to 127.0.0.2

**Comment by KyleBarton** [comment]
Pull Request: #4

**Comment by abuckley1** [comment]
this has been approved.

**Comment by abuckley1** [comment]
I verified this fix in production by jumping up and down.
